# @package _global_
job_name: prediction_MoE_pluto
py_func: train
objective_aggregate_mode: mean

defaults:
        - override /data_augmentation:
                  - contrastive_scenario_generator
        - override /splitter: nuplan
        - override /model: prediction_MoE_model
        - override /scenario_filter: training_scenarios_tiny
        - override /custom_trainer: prediction_MoE_trainer
        - override /lightning: custom_lightning
