# @package _global_
job_name: total_ensemble_pluto
py_func: train
objective_aggregate_mode: mean

defaults:
        - override /data_augmentation:
                  - contrastive_scenario_generator
        - override /splitter: nuplan
        - override /model: total_ensemble_model
        - override /scenario_filter: training_scenarios_tiny
        - override /custom_trainer: total_ensemble_trainer
        - override /lightning: custom_lightning
